MODEL:
  META_ARCHITECTURE: "Detr"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [18.892, 18.892, 18.892] # MUSCIMA++
  PIXEL_STD: [66.788, 66.788, 66.788] # MUSCIMA++
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DETR:
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NUM_OBJECT_QUERIES: 600
    NUM_CLASSES: 116
DATASETS:
  TRAIN: ("muscima_training",)
  TEST: ("muscima_validation",)
SOLVER:
  CHECKPOINT_PERIOD: 110880 # Maxiter/5
  IMS_PER_BATCH: 1
  BASE_LR: 0.0001
  # STEPS: (369600,) # Detr default
  # MAX_ITER: 554400 # Detr default
  STEPS: (15400,)
  MAX_ITER: 23100
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 4000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
