_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [21.409, 21.409, 21.409] # MUSCIMA++
  PIXEL_STD: [70.717, 70.717, 70.717] # MUSCIMA++
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 115
  ANCHOR_GENERATOR:
    SIZES: [[8, 16, 128]]
    ASPECT_RATIOS: [[0.125, 0.5, 1.0, 2.0, 8.0]]
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("muscima_training",)
  TEST: ("muscima_validation",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  BASE_LR: 0.001
  STEPS: (18000,)
  MAX_ITER: 24000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 4800
TEST:
  EVAL_PERIOD: 8000
OUTPUT_DIR: output